#!/usr/bin/env bash

# INPUT: a .prof file
# OUTPUT: recompiles the app with the passed profile and returns the ref profile (which might differ from the passed profile)

PROFILE=${1?"ERROR:NEED TO PROVIDFE A PROFILE"}


CHURNED_PROFILE="/tmp/churn_churned_profile.txt"

./compileWith $PROFILE
adb pull /data/misc/profiles/ref/com.google.android.apps.maps/primary.prof $CHURNED_PROFILE 2>&1 >/dev/null
cat $CHURNED_PROFILE
