#!/usr/bin/env bash

#Prints out a version of this profile where everything is hot

PROFILE=${1}
DUMP="/tmp/convertToH_dump.txt"
HOT_DUMP="/tmp/convertToH_hot_dump.txt"

./profileToDump $PROFILE > $DUMP
cat $DUMP | sed 's/^H//' | sed 's/^/H/' > $HOT_DUMP
cat $DUMP | grep '^L' >> $HOT_DUMP

./dumpToProfile $HOT_DUMP
