#!/usr/bin/env bash

#INPUT: a dump file corresponding to the specified package (or maps default)
#OUTPUT: creates a profile from the classes-and-methods dump and echos it

DUMP=${1?"ERROR: need to provide a dump file"}
PACKAGE=${2:-com.google.android.apps.maps}

if [ ! -f "$DUMP" ]  || [ "${DUMP##*.}" != "txt" ]
then
	>&2 echo "ERROR: provided dump is not a valid .txt file"
	exit 1
fi

PHONE_DUMP="/sdcard/profiles/dump.txt"
PHONE_PROFILE="/sdcard/profiles/profileIntersection_intersection.prof"


APK_LOCATION=$(adb shell "ls /data/app/${PACKAGE}*/base.apk")
adb push $DUMP $PHONE_DUMP 2>&1 >/dev/null
adb shell "profman --create-profile-from=$PHONE_DUMP --apk=$APK_LOCATION --dex-location=base.apk --reference-profile-file=$PHONE_PROFILE" 2>&1 >/dev/null
adb shell cat $PHONE_PROFILE

