#!/usr/bin/env bash

# INPUT: a .prof or .txt file
# OUTPUT: a method-class dump. 
# If a .txt file is passed, it is enterpretted as the dump to be returned.
# If a .prof file is passed, it is converted to a dump and returned.


FILE=${1?"ERROR: must provide a file"}

if [ "${FILE##*.}" = "prof" ]
then
        ./profileToDump $FILE
elif [ "${FILE1##*.}" = "txt" ]
then
         cat $FILE
else
        >&2 echo "ERROR: file \"${FILE}\" must have extension txt or prof"
        exit 1
fi
