#!/usr/bin/env bash


#INPUT: any number of .prof files stored locally
#OUTPUT: a new .prof stored at /tmp/profileUnion_union.prof (whose class/object dump is the union of the dumps of alll passed profiles)


PROF_DUMP="/tmp/profileUnion_prof_dump.txt"
UNION_DUMP="/tmp/profileUnion_union_dump.txt"
UNION_PROF="/tmp/profileUnion_union.prof"

MAPS_PACKAGE="com.google.android.apps.maps"
APK_LOCATION=$(adb shell "ls /data/app/${MAPS_PACKAGE}*/base.apk")

echo -n "" > $UNION_DUMP
for PROF in "$@"
do
	./profileToDump $PROF >> $UNION_DUMP
done

./dumpToProfile $UNION_DUMP
