#!/usr/bin/env bash





#Takeout
#./megaTest CUJS/aGMM_Latency_Transitions/Takeout/4_Takeout_placesheet_directionResults.txt e u f p c a 
./megaTest CUJS/aGMM_Latency_Transitions/Takeout/5_Takeout_directionResults_navigation.txt e u f p c a
#./megaTest CUJS/aGMM_Latency_Transitions/Takeout/7_Takeout_search_searchResults.txt e u f p c a
#./megaTest CUJS/aGMM_Latency_Transitions/Takeout/9_Takeout_searchResults_placeSheet.txt e u f p c a
./megaTest CUJS/aGMM_Latency_Transitions/Takeout/14_Takeout_appStart_directionResults.txt e u f p c a
./megaTest CUJS/aGMM_Latency_Transitions/Takeout/15_Takeout_appStart_navigation.txt   e u f p c a
./megaTest CUJS/aGMM_Latency_Transitions/Takeout/16_Takeout_placeSheet_navigation.txt e u f p c a
./megaTest CUJS/aGMM_Latency_Transitions/Takeout/1X7945_Takeout_openApp_thru_navigation.txt e u f p c a


./megaTest CUJS/aGMM_Latency_Transitions/12_appStart_searchResults.txt e u f p c a
./megaTest CUJS/aGMM_Latency_Transitions/13_appStart_placesheet.txt e u f p c a

