#!/usr/bin/env bash

#Copyright 2020 Google LLC
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

INPUT_FILE=${1:-input.txt}
INCLUDE_MEASURED_CUJ=${2?"ERROR: need to specify whether the measured CUJ should be included in the profile"}
FILE_NAME="${INPUT_FILE%.*}"
RECORD=$(sed '4q;d' $INPUT_FILE)

#ADD HEADER FOR DATA
echo "SIZE DATA:" > profile_manipulation_output.txt
echo "" >> profile_manipulation_output.txt

echo "Resetting the profile...."
adb shell cmd package compile --reset com.google.android.apps.maps

#Get the desired actions into the profile:
if [ "$INCLUDE_MEASURED_CUJ" = "y" ] || [ "$INCLUDE_MEASURED_CUJ" = "n" ] 
then
	echo "Adding the desired actions to the profile...."
	./runCujNTimes $INPUT_FILE $INCLUDE_MEASURED_CUJ 1

	echo "Waiting..."
	sleep 60

	#adb shell am force-stop com.google.android.apps.maps
	PROFILE_SIZE=$(adb shell stat -c%s /data/misc/profiles/cur/0/com.google.android.apps.maps/primary.prof)
	echo "size of profile is $PROFILE_SIZE" >> "profile_manipulation_output.txt"
	
	echo "Recompiling profile..."
	adb shell cmd package compile -m speed-profile -f com.google.android.apps.maps
elif [ "$INCLUDE_MEASURED_CUJ" = "a" ] 
then 
	echo "compiling everything..."
	adb shell cmd package compile -m everything -f com.google.android.apps.maps
fi


APP_SIZE=$(adb shell ls -l /data/app/com.google.android.apps.maps*/oat/arm64)
echo "app has size $APP_SIZE" >> "profile_manipulation_output.txt"
cat profile_manipulation_output.txt

echo "Executing and measuring the CUJ..."
./executeCuj $INPUT_FILE

#NNNNNEEEEEEEEEEED TO UPDATE THIS TO INCLUDE ALL AND EMPTY
if [ "$RECORD" = "r" ] && [ -f "median_clip.mp4" ]
then 
	if [ "$INCLUDE_MEASURED_CUJ" = "y" ]
	then 
		YESORNO="yes"
	else 
		YESORNO="no"
	fi
	OUTPUT="${FILE_NAME}_${YESORNO}_in_profile.mp4"
	mv median_clip.mp4 $OUTPUT
	echo "output file is called: $OUTPUT"
fi
