#!/usr/bin/env bash

##
# Loops through all provided compilation flags 5 times, each time recompiling aGMM as specified and measuring the desired portion of the CUJ specified by INPUT_FILE.
# Appends the SHORT_SUMMARY from each run to the AGGREGATED_DATA_FILE for the specified INPUT_FILE.
# Stores the following files at /mega_data/<INPUT_FILE_NAME>/<DATE>/:
# - (all_data.txt) a log containing formatted data from each measurement (acquired via a call to manipulateProfilesAndTest).
# - (summary.txt) a summary containing average action durations for each compilation flag (over all iterations).
#
# @param INPUT_FILE (Formatted with the following on consecutive lines: PRE-CUJ, POST_CUJ, NUM_ITERS, and optionally RECORD (a line with an "r" to indicate that you'd like to record). See CUJS/ for an example file.
# @param COMPILATION_FLAGS (all arguments after INPUT_FILE, e - empty profile, p - compile actions in Pre-CUJ, c - compile entire CUJ, a - compile all code).

# Example: ./megaTest CUJS/takeout.txt e p c a 
# Result: Will loop through compiling on an empty profile, one containing the pre-CUJ, one containing the entire CUJ and one containing all of aGMM, measuring the desired CUJ each time (as specified by the takeout file).
#
# Example: ./megaTest CUJS/takeout.txt a e
# Result: Will alternate between compiling all of aGMM and compiling nothing, measuring the desired CUJ each time (as specified by the takeout file).




INPUT_FILE=${1:-input.txt}
PRE_CUJ=$(sed '1q;d' $INPUT_FILE)
POST_CUJ=$(sed '2q;d' $INPUT_FILE)
ITERS=$(sed '3q;d' $INPUT_FILE)
RECORD=$(sed '4q;d' $INPUT_FILE)
POST_CUJ_STR_ARRAY=$(./peelHardBrackets $POST_CUJ) #peel off hard brackets
LOOPS=2 #Probably should make this an input
let "TOTAL_ITERS=$ITERS * $LOOPS"

#Initializing variables
SHORT_SUMMARY="/tmp/short_summary.txt" #location where ./manipulateProfilesAndTest will dump a short summary of time data and size of profile/app
APP_SIZE_DATA="/tmp/app_size.txt" #location where ./manipulateProfilesAndTest will dump the app size
MPT_FOLDER_DATA="/tmp/mpt_folder.txt" #location where ./manipulateProfilesAndTest will dump its folder
DATE=$(date '+%m-%d-%Y--%H:%M:%S')
RAW_DURATIONS="/tmp/raw_durations.txt"
INPUT_FILE_NAME="${INPUT_FILE##*/}" #remove folders from file name
INPUT_FILE_NAME="${INPUT_FILE_NAME%.*}" #remove file extension from file name
DATA_DUMP_FILE="/tmp/dumped_data.txt"
SUMMARY_TABLES="/tmp/megaTest_summaryTables.txt"

#Create the folder hierarchy for the data produced by the test, if it doesn't exist
FOLDER="mega_data/${INPUT_FILE_NAME}"
mkdir $FOLDER  2> /dev/null
FOLDER="mega_data/${INPUT_FILE_NAME}/${DATE}"
mkdir $FOLDER  2> /dev/null
AGGREGATED_DATA_FILE="${FOLDER}/all_data.txt"
TEST_SUMMARY="${FOLDER}/summary.txt"
CPU_STATUSES=$(./getCPUs)
shift ##shift args such that remaining args are the compilation settings

#Headers/Footers
HEADER_FOOTER="-----------------------------------------------------------------CPU STATUSES: $CPU_STATUSES----------COMPILATION FLAGS: $@----------$DATE-----------------------------------------------------------------" 
SUMMARY_HF="\n************************************************MEGA TEST SUMMARY:*************************************************"

echo "" > $DATA_DUMP_FILE

echo "force-stopping app..."
adb shell am force-stop com.google.android.apps.maps

echo "warming up..."
./runCujNTimes $INPUT_FILE w 0

echo $HEADER_FOOTER > $AGGREGATED_DATA_FILE
echo $HEADER_FOOTER 

echo -e $SUMMARY_HF > $TEST_SUMMARY
echo "PRE CUJ:      $PRE_CUJ" >> $TEST_SUMMARY
echo "MEASURED CUJ: $POST_CUJ" >> $TEST_SUMMARY
echo "" >> $TEST_SUMMARY

for ((run=0;run<$LOOPS;run++))
do
	for COMPILATION_FLAG in "$@"
	do
		echo "DOING $COMPILATION_FLAG TEST..." 
		./manipulateProfilesAndTest $INPUT_FILE $COMPILATION_FLAG
		echo "" >> $AGGREGATED_DATA_FILE
		cat $SHORT_SUMMARY >> $AGGREGATED_DATA_FILE
		APP_SIZE=$(cat $APP_SIZE_DATA)
		MPT_FOLDER=$(cat $MPT_FOLDER_DATA)
		STRING_DURATIONS=$(cat $RAW_DURATIONS)
		STRING_DURATIONS=$(./peelHardBrackets "$STRING_DURATIONS") #peel off hard brackets
		echo $APP_SIZE >> $DATA_DUMP_FILE
		echo $MPT_FOLDER >> $DATA_DUMP_FILE
		echo "$STRING_DURATIONS" >> $DATA_DUMP_FILE
		echo "" >> $DATA_DUMP_FILE
	done
done

echo "Generating mega test summary..."
java dataAggregation.AggregateMegaData "$DATA_DUMP_FILE" "$SUMMARY_TABLES" "$POST_CUJ_STR_ARRAY" "$TOTAL_ITERS" "$FOLDER" "$*"


cat $SUMMARY_TABLES >> $TEST_SUMMARY
echo -e $SUMMARY_HF >> $TEST_SUMMARY

#format spacing and cat data summary to aggregated data file
cat $TEST_SUMMARY >> $AGGREGATED_DATA_FILE
echo "" >> $AGGREGATED_DATA_FILE
echo $HEADER_FOOTER >> $AGGREGATED_DATA_FILE

#Display the summary table
cat $TEST_SUMMARY
echo $HEADER_FOOTER 
