#!/usr/bin/env bash

FILE=${1?"ERROR: need to provide a file"}

# INPUT: a .prof file or a method-class dump of a .prof file
# OUTPUT: stores two dump files, one with all of the dump entries that have their corresponding class in the original profile and the other which holds all other entries
#         echos the number of entries with each tag in each file


#If we are provided a profile, convert it to it's dump. If we were given a text file, interpret it as the dump
if [ "${FILE##*.}" = "prof" ]
then
	DUMP="/tmp/methodClassBacking_dump.txt"
	./profileToDump $FILE > $DUMP
elif [ "${FILE##*.}" = "txt" ]
then
	DUMP=$FILE
else
	echo "ERROR: file must have extension txt or prof"
	exit 1
fi



NON_BACKED="/tmp/methodClassBacking_non_backed.txt"
BACKED="/tmp/methodClassBacking_backed.txt"
echo -n "" > $NON_BACKED
echo -n "" > $BACKED


for CLASS in $(sed 's/^[HSPL]*//' $DUMP | sed 's/->.*//' | sort -u) #Iterate through the classes attached to each entry
do
	L_ENTRY=$(grep "^L${CLASS}" $DUMP)
	if [ "$L_ENTRY" = "" ]
	then
		grep "^[HSPL]*${CLASS}" $DUMP >> $NON_BACKED
	else 
		grep "^[HSPL]*${CLASS}" $DUMP >> $BACKED

	fi

done
echo "NON_BACKED SUMMARY:"
./dumpSummary $NON_BACKED
echo ""
echo "BACKED SUMMARY:"
./dumpSummary $BACKED
echo ""

