#!/usr/bin/env bash

PROFILE=${1?"ERROR: need to provide a profile"}
DUMP="/tmp/profSummaries_dump.txt"
CHURNED_PROFILE="/tmp/profSummaries_churned_profile.txt"

./compileWith $PROFILE
SIZE_DATA=$(adb shell ls -l /data/app/com.google.android.apps.maps*/oat/arm64)
APP_SIZE=$(echo $SIZE_DATA | awk '{print $2}')

echo $APP_SIZE
