#!/usr/bin/env bash

PROFILE1=${1?"ERROR: need to provide two profiles"}
PROFILE2=${2?"ERROR: need to provide two profiles"}


DUMP1="/tmp/profileComparison_dump1.txt"
DUMP2="/tmp/profileComparison_dump2.txt"



./profileToDump $PROFILE1 > $DUMP1
./profileToDump $PROFILE2 > $DUMP2


./dumpComparison $DUMP1 $DUMP2
