#!/usr/bin/env bash

#INPUT: a profile
#OUTPUT: prints the classes-and-methods dump to stdout

PROFILE=${1?"ERROR: need to provide an input .prof file"}
PACKAGE=${2:-com.google.android.apps.maps}

if [ ! -f "$PROFILE" ]  || [ "${PROFILE##*.}" != "prof" ]
then
        >&2 echo "ERROR: provided profile: "$PROFILE" is not a valid .prof file"
        exit 1
fi


PHONE_PROFILE="/sdcard/profiles/profileToDump_phone_profile.prof"


APK_LOCATION=$(adb shell "ls /data/app/${PACKAGE}*/base.apk")

adb push $PROFILE $PHONE_PROFILE 2>&1 >/dev/null
adb shell "profman --dump-classes-and-methods --profile-file=$PHONE_PROFILE --apk=$APK_LOCATION"
