#!/usr/bin/env bash

#Prints out a version of this profile where everything is hot

PROFILE=${1?"ERROR:NEED TO PROVIDFE A PROFILE"}

DUMP="/tmp/stableProfile_dump.txt"

CHURNED_DUMP="/tmp/stableProfile_churned_dump.txt"
CHURNED_PROFILE="/tmp/stableProfile_churned_profile.prof"

./churn $PROFILE > $CHURNED_PROFILE

./profileToDump $CHURNED_PROFILE | sort > $CHURNED_DUMP
./profileToDump $PROFILE | sort > $DUMP

diff $DUMP $CHURNED_DUMP
EXIT_CODE=$?

if [ $EXIT_CODE = "0" ]
then
	echo "STABLE!"
	exit 0
else 
	echo "BAD!"
	exit 1
fi
