#!/usr/bin/env bash

# INPUT: a .prof file
# OUTPUT: a message saying whether the profile is stable.
#         (a profile is stable if, when the app is compiled with it, the dump of the ref profile contains the same entries as the dump of the original profile).

PROFILE=${1?"ERROR: need to provide a .prof file"}

DUMP="/tmp/stableProfile_dump.txt"

CHURNED_DUMP="/tmp/stableProfile_churned_dump.txt"
CHURNED_PROFILE="/tmp/stableProfile_churned_profile.prof"

./churn $PROFILE > $CHURNED_PROFILE

./profileToDump $CHURNED_PROFILE | sort > $CHURNED_DUMP
./profileToDump $PROFILE | sort > $DUMP

diff $DUMP $CHURNED_DUMP
EXIT_CODE=$?

if [ $EXIT_CODE = "0" ]
then
	echo "STABLE!"
	exit 0
else 
	echo "NOT STABLE!"
	exit 1
fi
