#!/usr/bin/env bash


# INPUT: a profile or a profile dump
# OUTPUT: the counts of dump entries in the following order: HSPL, HPL, PL, L

FILE=${1?"ERROR: need to provide a file"}

DUMP="/tmp/profileTagCounts_dump.txt"


./fileToDump $FILE > $DUMP

counts=$(grep -o "^[HSPL]*" $DUMP | uniq -c)


i=0
for data in $counts
do
	if [ $(($i%2)) = "0" ]
	then	
		count=$data
	else 
		tag=$data
		((${tag}=$count))
	fi
	((i++))
done 

TAGS="HSPL HPL PL L"
for TAG in $TAGS
do
	echo -n "${TAG}: ${!TAG:-0}; "
done
echo ""
