#!/usr/bin/env bash

#SCRIPT TO ADD A TIME BOX TO A VIDEO
INPUT_FILE=${1:-input.txt}
FILE_NAME="${INPUT_FILE%.*}"
OUTPUT_FILE="${FILE_NAME}_timestamped.mp4"
ffmpeg -i $INPUT_FILE -filter_complex "drawtext=fontfile=/usr/share/fonts/truetype/DroidSans.ttf: text='%{pts \:flt}':fontsize=45 : x=(w-tw)/2: y=(1.2*lh): fontcolor=white: box=1: boxcolor=0x00000000@1" -c:a copy $OUTPUT_FILE

echo "output is called $OUTPUT_FILE"
